src/Entity/Issue.php
<?php

namespace Kalitics\SupportBundle\Entity;

use App\Entity\User\User;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gitlab\Api\Issues;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="Kalitics\SupportBundle\Repository\IssueRepository")
 * @ORM\Table(name="support_issues")
 */
class Issue
{

    const TYPE_NEW          = 'new';
    const TYPE_SUPPORT      = 'support';
    const TYPE_BUG          = 'bug';

    const LABEL_TO_CLARIFY          = 'wf::A clarifier';
    const WF_A_ARBITRER             = 'wf::16-à arbitrer';
    const WF_WAITING_DEV_ESTIMATE   = 'wf::17-à chiffrer DEV';
    const WF_WAITING_APPROVAL       = 'wf::18-à valider client';
    const WF_BACKLOG                = 'wf::20-backlog';

    /**
     * @var integer $id
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=250, nullable=false)
     */
    private $subject;

    /**
     * @var string
     * @ORM\Column(type="string", length=4000, nullable=true)
     */
    private $description;

    /**
     * @var string
     * @ORM\Column(type="string", length=4000, nullable=true)
     */
    private $link;

    /**
     * @var string
     * @ORM\Column(type="string", length=250, nullable=false)
     */
    private $type;

    /**
     * @var string
     * @ORM\Column(type="string", length=250)
     */
    private $status;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $isUrgent;

    /**
     * @var
     * @ORM\Column(type="json", name="labels", nullable=true)
     */
    private $labels;

    /**
     * @var integer $gitlabId
     * @ORM\Column(type="integer", nullable=true)
     */
    private $gitlabId;

    /**
     * @var integer $iid
     * @ORM\Column(type="integer", nullable=true)
     */
    private $iid;

    /**
     * @var string $gitlabUrl
     * @ORM\Column(type="string", nullable=true)
     */
    private $gitlabUrl;

    /**
     * @var string $gitlabImageUrl
     * @ORM\Column(type="string", nullable=true)
     */
    private $gitlabImageUrl;

    /**
     * @var string $gitlabImageMarkdown
     * @ORM\Column(type="string", nullable=true)
     */
    private $gitlabImageMarkdown;

    /**
     * @var string $gitlabImageMarkdown
     * @ORM\Column(type="string", nullable=true)
     */
    private $gitlabHumanTimeEstimate;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $informationsPosted;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true)
     */
    private $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true)
     */
    private $validatedBy;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $validatedAt;

    /**
     * Issue constructor.
     * @param User $createdBy
     * @throws \Exception
     */
    public function __construct(?User $createdBy = null)
    {

        $this->createdBy = $createdBy;

        $this->setCreatedAt(new \DateTime("now"));
        $this->setUpdatedAt(new \DateTime("now"));
        $this->setStatus(Issues::STATE_OPENED);

        $this->setSubject("");
        $this->setDescription("");
        $this->setType("");
        $this->setLink("");
        $this->setIsUrgent(false);
        $this->setInformationsPosted(false);
        $this->setIid(0);

        //Par défaut un tiquet n'est jamais validé
        $this->setValidatedAt(null);
        $this->setValidatedBy(null);
        $this->setGitlabHumanTimeEstimate(null);
    }

    /**
     * @return string
     */
    public function getGitlabHumanTimeEstimate(): string
    {
        return $this->gitlabHumanTimeEstimate ?? "Pas d'estimation";
    }

    /**
     * @param string $gitlabHumanTimeEstimate
     */
    public function setGitlabHumanTimeEstimate($gitlabHumanTimeEstimate): void
    {
        $this->gitlabHumanTimeEstimate = $gitlabHumanTimeEstimate;
    }

    /**
     * @param $label
     * @return $this
     */
    public function addLabel($label){

        $issueLabels = $this->getLabels();

        if(!in_array($label, $issueLabels)){
            $issueLabels[] = $label;
            $this->setLabels($issueLabels);
        }

        return $this;

    }

    /**
     * @param $label
     * @return $this
     */
    public function removeLabel($label){
        $issueLabels = $this->getLabels();

        if(in_array($label, $issueLabels)){
            $labelKey = array_search($label, $issueLabels);
            unset($issueLabels[$labelKey]);
            $this->setLabels($issueLabels);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getValidatedBy()
    {
        return $this->validatedBy;
    }

    /**
     * @param mixed $validatedBy
     */
    public function setValidatedBy($validatedBy): void
    {
        $this->validatedBy = $validatedBy;
    }

    /**
     * @return mixed
     */
    public function getValidatedAt()
    {
        return $this->validatedAt;
    }

    /**
     * @param mixed $validatedAt
     */
    public function setValidatedAt($validatedAt): void
    {
        $this->validatedAt = $validatedAt;
    }

    /**
     * @return string
     */
    public function getGitlabImageMarkdown(): string
    {
        return (string)$this->gitlabImageMarkdown;
    }

    /**
     * @param string $gitlabImageMarkdown
     */
    public function setGitlabImageMarkdown(string $gitlabImageMarkdown): void
    {
        $this->gitlabImageMarkdown = $gitlabImageMarkdown;
    }

    /**
     * @return string|null
     */
    public function getGitlabImageUrl(): ?string
    {
        return $this->gitlabImageUrl;
    }

    /**
     * @param string $gitlabImageUrl
     */
    public function setGitlabImageUrl(?string $gitlabImageUrl): void
    {
        $this->gitlabImageUrl = $gitlabImageUrl;
    }

    /**
     * @return bool
     */
    public function isInformationsPosted(): bool
    {
        return $this->informationsPosted;
    }

    /**
     * @param bool $informationsPosted
     */
    public function setInformationsPosted(bool $informationsPosted): void
    {
        $this->informationsPosted = $informationsPosted;
    }

    /**
     * @return string
     */
    public function getGitlabUrl(): string
    {
        return $this->gitlabUrl;
    }

    /**
     * @param string $gitlabUrl
     */
    public function setGitlabUrl(string $gitlabUrl): void
    {
        $this->gitlabUrl = $gitlabUrl;
    }

    /**
     * @return int
     */
    public function getIid(): int
    {
        return $this->iid;
    }

    /**
     * @param int $iid
     */
    public function setIid(int $iid): void
    {
        $this->iid = $iid;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param mixed $updatedAt
     */
    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return int
     */
    public function getGitlabId(): int
    {
        return $this->gitlabId;
    }

    /**
     * @param int $gitlabId
     */
    public function setGitlabId(int $gitlabId): void
    {
        $this->gitlabId = $gitlabId;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return bool
     */
    public function isUrgent(): bool
    {
        return $this->isUrgent;
    }

    /**
     * @param bool $isUrgent
     */
    public function setIsUrgent(bool $isUrgent): void
    {
        $this->isUrgent = $isUrgent;
    }

    /**
     * @return mixed
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @return string
     */
    public function getSubject(): string
    {
        return $this->subject;
    }

    /**
     * @param string $subject
     */
    public function setSubject(string $subject): void
    {
        $this->subject = $subject;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return string
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * @param string $link
     */
    public function setLink($link): void
    {
        $this->link = $link;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @param $status
     */
    public function setStatus($status)
    {
        if (!in_array($status, array(Issues::STATE_OPENED, Issues::STATE_CLOSED))) {
            throw new \InvalidArgumentException("Invalid status");
        }
        $this->status = $status;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function __toString()

src/Resources/views/_includes/_btn.html.twig
{% if app.user.hasRole('support_simple_write') or app.user.hasRole('support_full_write') or app.user.hasRole('support_validate') %}
    <a class="kt-header__topbar-icon" data-toggle="modal" data-target="#git_submit_issue_modal"><i class="fa fa-headset"></i></a>
{% elseif app.user.hasRole('support_simple_read') %}
    <a href="{{ path('kalitics_support_view') or app.user.hasRole('support_full_read') }}" class="kt-header__topbar-icon"><i class="fa fa-headset"></i></a>
{% endif %}

src/Resources/views/_includes/_edit_modal_content.html.twig
<div class="modal-header">
    <h4 class="modal-title">Modifier un bug ou une demande d'amélioration</h4>
</div>
<div class="modal-body">

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">

            {{ form_start(form, {'action': path('kalitics_support_edit_issue', {'id' : issue.gitlabId}), 'method': 'POST', 'attr': {'id':'git_edit_submit_form'}}) }}
                {{ form_widget(form) }}
            {{ form_end(form) }}

        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 pull-right">
            <a href="{{ path('kalitics_support_view') }}">Voir tous les tickets</a>
        </div>
    </div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-label-danger" data-dismiss="modal">Fermer</button>
    <a onClick="$('#git_edit_submit_form').submit();" class="btn btn-label-success">Soumettre</a>
</div>

src/Resources/views/_includes/_form.html.twig
{{ form_start(form, {'action': path('kalitics_support_display_form'), 'method': 'POST', 'attr': {'id':'git_submit_form'}}) }}

    <div class="form-group row">
        {{ form_label(form.subject) }}
        <div class="col-sm-9">
            {{ form_widget(form.subject, {'attr': {'onkeyup': "filterIssuesByName('submit_issue_subject');"}}) }}
        </div>
    </div>

    {{ form_row(form.type) }}
    {{ form_row(form.isUrgent) }}
    <div class="form-group row">
        {{ form_label(form.link) }}
        <div class="col-sm-9">
            {{ form_widget(form.link, {'attr': {'value': uri}}) }}
        </div>
    </div>

    {{ form_widget(form) }}

{{ form_end(form) }}

src/Resources/views/_includes/_list.html.twig
<div class="row">
    <div class="col-sm-8 kt-margin-b-10">
        <input id="input_filter_issue_name" onkeyup="filterIssuesByName('input_filter_issue_name');" class="form-control w-100" value="" placeholder="Rechercher">
    </div>
    <div class="col-sm-4 kt-margin-b-10">
        <select id="select_filter_issue_status" class="form-control w-100" onchange="filterByStatus();">
            <option value="tous">Tous</option>
            <option value="opened">Ouverts</option>
            <option value="closed">Cloturés</option>
        </select>
    </div>
</div>

<div class="kt-notification-v2">
    {% for issue in issues %}

        <div class="row kt-margin-b-0">
            <div class="col-sm-12">
                <a class="issue_{{ issue.id }} alert alert-outline-{% if issue.status == 'opened' %}brand{% else %}success{% endif %} kt-notification-v2__item kalitics_support_issue kalitics_support_issue_{{ issue.status }}" style="">
                    <div class="kt-notification-v2__item-icon pointer" onclick="toggleIssue('{{ issue.Id }}');">

                        {% if issue.type == 'support' %}
                            <i class="fa fa-phone kt-font-primary"></i>
                        {% elseif issue.type == 'new' %}
                            <i class="fa fa-plus kt-font-success"></i>
                        {% else %}
                            <i class="fa fa-bug kt-font-warning"></i>
                        {% endif %}

                    </div>
                    <div class="kt-notification-v2__itek-wrapper">
                        <div class="kt-notification-v2__item-title">
                            <div class="row pointer" onclick="toggleIssue('{{ issue.id }}');">
                                <div class="kalitics_issue_title col-sm-8">
                                    <span style="color: rgba(0, 0, 0, 0.2);padding-right: 5px;">#{{ issue.iid }}</span> {{ issue.subject }}

                                    {% if issue.urgent or issue.createdBy is not null %}<br/>{% endif %}
                                    {% if issue.urgent %}
                                        <span class="kt-badge kt-badge--danger kt-badge--inline kt-badge--pill kt-margin-r-5">Bloquant</span>
                                    {% endif %}
                                    {% if issue.createdBy is not null %}
                                        <span class="kt-notification-v2__item-desc">Soumis par : {{ issue.createdBy }}</span>
                                    {% endif %}

                                </div>
                                <div class="col-sm-4 pull-right">
                                    {{ issue.createdAt | date('d/m/Y H:i') }}
                                    <br/>

                                    {% if constant('Kalitics\\SupportBundle\\Entity\\Issue::LABEL_TO_CLARIFY') in issue.labels %}
                                        <span class="kt-badge kt-badge--warning kt-badge--inline kt-badge--pill">
                                            Demande d'informations supplémentaires
                                        </span>
                                    {% endif %}

                                    {% if constant('Kalitics\\SupportBundle\\Entity\\Issue::WF_WAITING_APPROVAL') in issue.labels %}
                                        <span class="kt-badge kt-badge--warning kt-badge--inline kt-badge--pill">
                                            En attente de validation par un responsable
                                        </span>
                                    {% endif %}

                                    {% if issue.status == 'opened' %}
                                        <span class="kt-badge kt-badge--brand kt-badge--inline kt-badge--pill">En cours de résolution</span>
                                    {% else %}
                                        <span class="kt-badge kt-badge--success kt-badge--inline kt-badge--pill">Résolu</span>
                                    {% endif %}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12" id="support_kalitics_issue_id_{{ issue.id }}" style="display: none;">

                                    <div class="row">
                                        <div class="col-sm-12">
                                            <hr>
                                            {% if issue.gitlabImageUrl is not null %}
                                                <form id="{{ issue.id }}_img_form" action="https://gitlab.com/{{ issue.gitlabImageUrl }}" style="display: inline-flex">
                                                    <button onclick="$('{{ issue.id }}_img_form').submit();" class="btn btn-label-primary"> <i class="la la-image"></i>Télécharger l'image associée</button>
                                                </form>
                                            {% endif %}

                                            {% if app.user.hasRole('SUPER_ADMIN') %}
                                                <form id="{{ issue.id }}_gitlab_form" action="{{ issue.gitlabUrl }}" style="display: inline-flex">
                                                    <button onclick="$('{{ issue.id }}_gitlab_form').submit();" class="btn btn-label-primary">
                                                        <img class="" style="height: 15px;margin-left: 5px;" src="https://gitlab.com/assets/favicon-7901bd695fb93edb07975966062049829afb56cf11511236e61bcf425070e36e.png">
                                                        Voir sur gitlab
                                                    </button>
                                                </form>
                                            {% endif %}

                                            {% if issue.status == 'opened' %}
                                                <button onclick="openIssueEditModal('{{ path('kalitics_support_edit_issue', {'id' : issue.gitlabId}) }}');" class="btn btn-label-primary"><i class="fa fa-edit"></i>Modifier</button>
                                                <button onclick="markIssueClosed('{{ path('kalitics_support_mark_closed', {'id' : issue.gitlabId}) }}', '{{ issue.gitlabId }}');" class="btn btn-label-success"><i id="issue_state_loader_{{ issue.gitlabId }}" class="fa fa-check"></i>Marquer résolu</button>

                                                {% if constant('Kalitics\\SupportBundle\\Entity\\Issue::WF_WAITING_APPROVAL') in issue.labels %}
                                                    <button onclick="window.location = '{{ path('kalitics_support_refuse_issue', {'id' : issue.id}) }}';" class="pull-right btn btn-label-danger"><i class="fa fa-trash"></i> Refuser</button>
                                                    <button onclick="window.location = '{{ path('kalitics_support_validate_issue', {'id' : issue.id}) }}';" class="pull-right btn btn-label-success"><i class="fa fa-check"></i> Valider la commande de <b>{{ issue.gitlabHumanTimeEstimate }}</b></button>
                                                {% elseif issue.validatedBy is not null %}
                                                    <span class="pull-right">Validé par {{ issue.validatedBy }} le {{ issue.validatedAt|date('d/m/Y') }}</span>
                                                {% endif %}

                                            {% endif %}

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-8">

                                            <div class="row">
                                                <div class="col-sm-12" style="background-color: #fff;padding: 10px;margin: 10px;">
                                                    {{ issue.description | nl2br }}
                                                    <br/><br/>
                                                    {{ issue.link }}
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-sm-4 pull-right pull-bottom">

                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}
</div>


<div class="modal fade" id="kalitics-support-modal-edit-issue" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

            <div class='modal-header'>
                <h4 class='modal-title' id='smallModalLabel'>Chargement ...</h4>
            </div>
            <div class='modal-body center'>
                <div class="center p-t-50 p-b-50">
                    <i class="fas fa-spinner fa-spin"></i>
                </div>
            </div>

        </div>
    </div>
</div>


<script>

    function toggleIssue(issue_id){

        var $issueBlock = $('#issue_'+issue_id);
        if( $issueBlock.hasClass('disabled') ){
            $issueBlock.removeClass('disabled');
        }else{
            $issueBlock.addClass('disabled');
        }
            $('#support_kalitics_issue_id_'+issue_id).toggle('slow');

    }

    function filterByStatus(){

        $status = $('#select_filter_issue_status').val();
        console.log('show '+$status);
        $('.kalitics_support_issue').hide();
        if($status == 'opened'){
            $('.kalitics_support_issue_opened').show();
        }
        if($status == 'closed'){
            $('.kalitics_support_issue_closed').show();
        }
        if($status == 'tous'){
            $('.kalitics_support_issue').show();
        }

    }

    function filterIssuesByName(input_id){
        var input, filter, ul, li, a, i, txtValue;
        filter = $('#'+input_id).val().toUpperCase();
        li = $('.kalitics_support_issue');
        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByClassName("kalitics_issue_title")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }

    function openIssueEditModal(path){
        //display loading modal
        $('#kalitics-support-modal-edit-issue').modal('show');
        $.ajax({
            url: path,
            type: 'GET',
            data: {},
            success: function(response){
                $('#kalitics-support-modal-edit-issue .modal-content').html(response);
            }
        });
    }

    function markIssueClosed(path, id){
        //display loading modal

        var $icon = $('#issue_state_loader_'+id);

        $icon.removeClass('fa-check');
        $icon.addClass('fa-spin fa-circle-notch');

        $.ajax({
            url: path,
            type: 'GET',
            data: {},
            success: function(response){
                loadIssuesList();
            }
        });
    }

</script>

src/Resources/views/_includes/_modal.html.twig
<div class="modal fade" id="git_submit_issue_modal" tabindex="-1" role="dialog" aria-labelledby="git_submit_issue_modal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Soumettre un bug ou une demande d'amélioration</h4>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div id="submit_git_issue_alerts" class="col-sm-12 col-md-12 col-lg-12" style="display: none;">

                        <div class="alert alert-danger" role="alert">
                            <div class="alert-text">
                                <div id="submit_git_issue_alerts_subject"><strong>- L'objet est trop court</strong></div>
                                <div id="submit_git_issue_alerts_description"><strong>- La corp du message est trop court, il doit faire au minimum 50 cacactères</strong></div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div id="submit_git_issue_form_container" class="col-sm-12 col-md-12 col-lg-12">
                        {{ render(controller('kalitics_support.controller.submission_controller:formAction', {'request' : app.request})) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 pull-right">
                        <a href="{{ path('kalitics_support_view') }}">Voir tous les tickets</a>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                <a onClick="checkAndSubmitGitLabIssue();" href="#" class="btn btn-label-success">Soumettre</a>
            </div>
        </div>
    </div>
</div>

<script>

    function checkAndSubmitGitLabIssue(){

        var $subject = $('#submit_issue_subject');
        var $subjectAlert = $('#submit_git_issue_alerts_subject');
        var $description = $('#submit_issue_description');
        var $descriptionAlert = $('#submit_git_issue_alerts_description');
        var $alertContainer = $('#submit_git_issue_alerts');

        var $isSubjectOk = true;
        var $isDescriptionOk = true;
        $subjectAlert.hide();
        $descriptionAlert.hide();
        $alertContainer.hide();

        console.log($subject.val().length);
        console.log($description.val().length);

        if($subject.val().length < 10){
            var $isSubjectOk = false;
            $alertContainer.show();
            $subjectAlert.show();
        }

        if($description.val().length < 50){
            var $isDescriptionOk = false;
            $alertContainer.show();
            $descriptionAlert.show();
        }

        if($isSubjectOk && $isDescriptionOk){
            $('#submit_git_issue_form_container form').submit();
        }
    }

</script>